# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55943c110ef97f7326dd21295eee7a43022b69ebfbfecdca4a8ba8692b88a1bc0f2f86d6cf75fac1e33212ced8d6530eab261402ca0ef503db38bf60ae349c5e

test:
  secret_key_base: 3fabf3d7c611f6b9110a968d19f1721789007283fd8c9d5f24f1ee9e6988aa381c225b432c582d6f716ae9341d12d2375259c71e0ad2fe8e60e43c950fd4948a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
